- targets:
    - "172.28.41.201:9003"  # dg5W-201
    - "172.28.41.202:9003"  # dg5W-202
    - "172.28.41.203:9003"  # dg5W-203
    - "172.28.41.204:9003"  # dg5W-204
  labels:
    role: "host_telemetry"
